### ISSUE TITLE
If strategy is not set, authentication fails

### ISSUE THREAD

**Issue by shawnlauzon** [MichaelErmer/feathers-authentication-compatibility#2]
If I try to use the the old endpoints without adding `strategy: 'local'`, I got the following failure:
```{
  "name": "NotAuthenticated",
  "message": "No auth token",
  "code": 401,
  "className": "not-authenticated",
  "data": {},
  "errors": {}
}

If I add it, things work. As it stands, clients need to add this field, and that's a problem for backwards compatibility.

I tried to fix this locally, but no matter what I did in the compatibility layer, the same auth token failure occurred. Perhaps you have a thought?

**Comment by MichaelErmer** [comment]
fixed and released as feathers-authentication-compatibility@1.2.0

**Comment by shawnlauzon** [comment]
This change doesn't seem to have any affect. I still get the same error when I don't include `	"strategy": "local`.
